### ISSUE TITLE
State of the mod

### ISSUE THREAD

**Issue by m1jordanallen** [sokratis12GR/WeaponsPlus#9]
Hello there.  I have been using your mod(s) for quite some time now and absolutely love them.  Thank you for all your hard work.  I come to you with a question with no expectation.  I noticed your mod has been removed from curse and I cannot seem to find any trace of it other than here.  Is this mod being scrapped?  If not, where may we find  builds and permissions for pack documentation?  If its temporary, I will be patient for it to return :)

**Comment by sokratis12GR** [comment]
@m1jordanallen WeaponsPlus has been integrated to ArmorPlus
